version: '3.3'
services:
  web:
    build:
      context: ./
    # Runs app.js,
    command: node app.js
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    volumes:
      # Points to a folder with .sql files to auto-load
      - ./database-file:/docker-entrypoint-initdb.d

