name: On push to develop branch

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Quickly check to show the workflow is running
      - name: check
        run: echo "First job done!"

      # Pulls down the repo code
      - uses: actions/checkout@v4

      # Installs Node
      - uses: actions/setup-node@v4

      # Confirms Node is set up
      - name: check node
        run: node --version

      - name: check dir
        run: ls

      # Creates a .env from the secret
      - name: Create the .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      #  Shows the .env content for debugging
      - name: Check
        run: cat .env

      # Installs dependencies (Node packages)
      - name: Install dependencies
        run: npm install

      # Spins up containers using the alternative compose file
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      # If you have Nightwatch or other tests:
      - name: get dependencies for tests
        run: sudo apt-get install -y xvfb

      - name: run the nightwatch tests
        run: xvfb-run --auto-servernum npm test -- --env chrome
